GET localhost:8080/api/examplepoems
###
GET http://localhost:8080/api/examplepoems/1
###
GET localhost:8080/api/examplepoemtype
###
GET localhost:8080/api/userpoems/
###
PATCH localhost:8080/api/user/227/poem
Content-Type: application/json

{ "poetName": "Jake",
"title": "Breathe",
"poemContent": "Greatest Poem Of All Times"
}
###
GET localhost:8080/api/userpoems/70
###
DELETE localhost:8080/api/userpoems/228
###
PUT localhost:8080/api/userpoems/227
Content-Type: application/json

{ "id": 259,
  "poetName": "Jake",
  "title": "Love Simon",
  "poemContent": "This is a Poem about loooooooove."
}
###
GET localhost:8080/api/user
###
POST localhost:8080/api/user
Content-Type: application/json

{
"userName": "Dylon"
}
###
GET localhost:8080/api/user/227